//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Self_Hosting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceKonwledgeAndResource
    {
        public int id { get; set; }
        public int resourceid { get; set; }
    }
}
