//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Self_Hosting.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainingEntities : DbContext
    {
        public TrainingEntities()
            : base("name=TrainingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdvanceKnowledge> AdvanceKnowledges { get; set; }
        public virtual DbSet<AdvanceKonwledgeAndResource> AdvanceKonwledgeAndResources { get; set; }
        public virtual DbSet<Exhibition> Exhibitions { get; set; }
        public virtual DbSet<ExhibitionType> ExhibitionTypes { get; set; }
        public virtual DbSet<ExpandKnowledge> ExpandKnowledges { get; set; }
        public virtual DbSet<Instance> Instances { get; set; }
        public virtual DbSet<Knowledge> Knowledges { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<ResourceType> ResourceTypes { get; set; }
        public virtual DbSet<UploadRecordForTeacher> UploadRecordForTeachers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
