//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNameFlewAway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceKnowledge
    {
        public int id { get; set; }
        public string key { get; set; }
        public string imageaddress { get; set; }
        public int resourceid { get; set; }
        public string description { get; set; }
        public string context { get; set; }
    }
}
