//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNameFlewAway.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 进阶知识
    /// </summary>
    public partial class AdvanceKnowledge
    {
        /// <summary>
        /// 进阶知识id
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// 进阶知识关键词（名字）
        /// </summary>
        public string key { get; set; }
        /// <summary>
        /// 进阶知识图片
        /// </summary>
        public string imageaddress { get; set; }
        /// <summary>
        /// 进阶知识描述
        /// </summary>
        public string description { get; set; }
        /// <summary>
        /// 进阶知识内容
        /// </summary>
        public string context { get; set; }

        /// <summary>
        /// 进阶知识全参构造函数
        /// </summary>
        /// <param name="id">进阶知识id</param>
        /// <param name="key">进阶知识关键词（名称）</param>
        /// <param name="imageaddress">进阶知识地址</param>
        /// <param name="description">进阶知识描述</param>
        /// <param name="context">进阶知识内容</param>
        public AdvanceKnowledge(int id, string key, string imageaddress, string description, string context)
        {
            this.id = id;
            this.key = key;
            this.imageaddress = imageaddress;
            this.description = description;
            this.context = context;
        }
        /// <summary>
        /// 进阶知识无参构造函数
        /// </summary>
        public AdvanceKnowledge()
        {

        }
    }
}
