//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNameFlewAway.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 作品展示
    /// </summary>
    public partial class Exhibition
    {
        /// <summary>
        /// 作品id
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// 作品名
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// 作者
        /// </summary>
        public string author { get; set; }
        /// <summary>
        /// 作品描述
        /// </summary>
        public string description { get; set; }
        /// <summary>
        /// 作品效果图
        /// </summary>
        public string showimage { get; set; }
        /// <summary>
        /// 作品类别id
        /// </summary>
        public int typeid { get; set; }
        /// <summary>
        /// 作品封面图片
        /// </summary>
        public string coverimage { get; set; }
        /// <summary>
        /// 资源地址
        /// </summary>
        public string resourceaddress { get; set; }

        /// <summary>
        /// 展示作品全参构造函数
        /// </summary>
        /// <param name="id">展示作品id</param>
        /// <param name="name">展示作品名称</param>
        /// <param name="author">展示作品作者</param>
        /// <param name="typeid">展示作品类别id</param>
        /// <param name="description">展示作品描述</param>
        /// <param name="showimage">展示作品效果图片</param>
        /// <param name="coverimage">展示作品封面图片</param>
        /// <param name="resourceaddress">展示作品资源地址</param>
        public Exhibition(int id, string author,string name, int typeid, string description, string showimage, string coverimage, string resourceaddress)
        {
            this.id = id;
            this.author = author;
            this.name = name;
            this.typeid = typeid;
            this.description = description;
            this.showimage = showimage;
            this.coverimage = coverimage;
            this.resourceaddress = resourceaddress;
        }
        /// <summary>
        /// 展示作品类别无参构造函数
        /// </summary>
        public Exhibition()
        {

        }
    }
}
