//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNameFlewAway.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 作品展示类别
    /// </summary>
    public partial class ExhibitionType
    {
        /// <summary>
        /// 类别id
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// 类别名称
        /// </summary>
        public string name { get; set; }

        /// <summary>
        /// 展示作品类别全参构造函数
        /// </summary>
        /// <param name="id">展示作品类别id</param>
        /// <param name="name">展示作品类别名称</param>
        public ExhibitionType(int id, string name)
        {
            this.id = id;
            this.name = name;
        }
        /// <summary>
        /// 展示作品类型无参构造函数
        /// </summary>
        public ExhibitionType()
        {

        }
    }
}
