//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNameFlewAway.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 拓展知识
    /// </summary>
    public partial class ExpandKnowledge
    {
        /// <summary>
        /// 拓展知识id
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// 拓展知识关键字（名称）
        /// </summary>
        public string key { get; set; }
        /// <summary>
        /// 拓展知识描述
        /// </summary>
        public string description { get; set; }
        /// <summary>
        /// 拓展知识链接地址
        /// </summary>
        public string url { get; set; }

        /// <summary>
        /// 拓展知识全参构造函数
        /// </summary>
        /// <param name="id">拓展知识id</param>
        /// <param name="key">拓展知识关键字（名称）</param>
        /// <param name="description">拓展知识描述</param>
        /// <param name="url">拓展知识链接</param>
        public ExpandKnowledge(int id, string key, string description, string url)
        {
            this.id = id;
            this.key = key;
            this.description = description;
            this.url = url;
        }
        /// <summary>
        /// 拓展知识无参构造函数
        /// </summary>
        public ExpandKnowledge()
        {

        }
    }
}
