//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNameFlewAway.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 实例
    /// </summary>
    public partial class Instance
    {
        /// <summary>
        /// 实例id
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// 实例地址
        /// </summary>
        public string resourceAddress { get; set; }
        /// <summary>
        /// 实例关键字（名称）
        /// </summary>
        public string key { get; set; }
        /// <summary>
        /// 实例图片
        /// </summary>
        public string image { get; set; }
        /// <summary>
        /// 实例题目
        /// </summary>
        public string title { get; set; }
        /// <summary>
        /// 实例代码
        /// </summary>
        public string code { get; set; }
        /// <summary>
        /// 实例讲解
        /// </summary>
        public string context { get; set; }
        /// <summary>
        /// 实例结果
        /// </summary>
        public string result { get; set; }

        /// <summary>
        /// 实例全参构造函数
        /// </summary>
        /// <param name="id">实例id</param>
        /// <param name="resourceAddress">实例资源地址</param>
        /// <param name="key">实例关键字（名称）</param>
        /// <param name="image">实例图片</param>
        /// <param name="title">实例题目</param>
        /// <param name="code">实例代码</param>
        /// <param name="context">实例内容</param>
        /// <param name="result">实例结果</param>
        public Instance(int id, string resourceAddress, string key, string image, string title, string code, string context, string result)
        {
            this.id = id;
            this.resourceAddress = resourceAddress;
            this.key = key;
            this.image = image;
            this.title = title;
            this.code = code;
            this.context = context;
            this.result = result;
        }
        /// <summary>
        /// 实例无参构造函数
        /// </summary>
        public Instance()
        {

        }
    }
}
