//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNameFlewAway.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 基础知识
    /// </summary>
    public partial class Knowledge
    {
        /// <summary>
        /// 基础知识id
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// 基础知识图片
        /// </summary>
        public string image { get; set; }
        /// <summary>
        /// 基础知识关键字（名称）
        /// </summary>
        public string key { get; set; }
        /// <summary>
        /// 基础知识资源地址
        /// </summary>
        public string resourceAddress { get; set; }
        /// <summary>
        /// 基础知识描述
        /// </summary>
        public string description { get; set; }
        /// <summary>
        /// 基础知识内容
        /// </summary>
        public string context { get; set; }

        /// <summary>
        /// 基础知识全参构造函数
        /// </summary>
        /// <param name="id">基础知识id</param>
        /// <param name="image">基础知识图片</param>
        /// <param name="key">基础知识关键字（名称）</param>
        /// <param name="resourceAddress">基础知识资源地址</param>
        /// <param name="description">基础知识描述</param>
        /// <param name="context">基础知识内容</param>
        public Knowledge(int id, string image, string key, string resourceAddress, string description, string context)
        {
            this.id = id;
            this.image = image;
            this.key = key;
            this.resourceAddress = resourceAddress;
            this.description = description;
            this.context = context;
        }
        /// <summary>
        /// 基础知识无参构造函数
        /// </summary>
        public Knowledge()
        {

        }
    }
}
