//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNameFlewAway.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 资源类别
    /// </summary>
    public partial class ResourceType
    {
        /// <summary>
        /// 资源类别id
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// 资源类别名
        /// </summary>
        public string name { get; set; }

        /// <summary>
        /// 资源类型全参构造函数
        /// </summary>
        /// <param name="id">资源id</param>
        /// <param name="name">资源名</param>
        public ResourceType(int id, string name)
        {
            this.id = id;
            this.name = name;
        }
        /// <summary>
        /// 资源类型无参构造函数
        /// </summary>
        public ResourceType()
        {

        }
    }
}
