//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNameFlewAway.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 用户信息
    /// </summary>
    public partial class User
    {
        /// <summary>
        /// 用户id
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// 用户名
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// 用户手机号
        /// </summary>
        public string phone { get; set; }
        /// <summary>
        /// 用户密码
        /// </summary>
        public string password { get; set; }
        /// <summary>
        /// 用户标识，0为学生，1为老师
        /// </summary>
        public Nullable<byte> status { get; set; }

        /// <summary>
        /// 用户全参构造函数
        /// </summary>
        /// <param name="id">用户id</param>
        /// <param name="name">用户名</param>
        /// <param name="phone">用户手机号</param>
        /// <param name="password">用户密码</param>
        /// <param name="status">用户标识</param>
        public User(int id, string name, string phone, string password, byte? status)
        {
            this.id = id;
            this.name = name;
            this.phone = phone;
            this.password = password;
            this.status = status;
        }

        /// <summary>
        /// 用户无参构造函数
        /// </summary>
        public User()
        {

        }
    }
}
