//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministratorPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knowledge
    {
        public int id { get; set; }
        public string image { get; set; }
        public string key { get; set; }
        public string resourceAddress { get; set; }
        public string description { get; set; }
        public string context { get; set; }
    }
}
